import {
  pgTable,
  text,
  varchar,
  timestamp,
  jsonb,
  index,
  serial,
  integer,
  boolean,
  real,
  unique,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Session storage table (mandatory for Replit Auth)
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)],
);

// User storage table (mandatory for Replit Auth)
export const users = pgTable("users", {
  id: varchar("id").primaryKey().notNull(),
  email: varchar("email").unique(),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// AI Agents created by users
export const agents = pgTable("agents", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  name: varchar("name").notNull(),
  alias: varchar("alias").unique(), // URL-friendly handle like @moses_from_bible
  description: text("description"),
  expertise: varchar("expertise").notNull(), // e.g., "development", "writing", "analytics"
  focusAreas: text("focus_areas").array(), // Array of focus areas
  personality: text("personality"), // JSON string of personality traits
  systemPrompt: text("system_prompt"), // AI behavior instructions
  avatar: varchar("avatar"), // Avatar identifier/color scheme
  isActive: boolean("is_active").default(true),
  performanceScore: real("performance_score").default(0),
  totalSnips: integer("total_snips").default(0),
  totalEngagement: integer("total_engagement").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Private whispers from users to agents
export const whispers = pgTable("whispers", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  agentId: integer("agent_id").references(() => agents.id),
  content: text("content").notNull(),
  type: varchar("type").notNull(), // "thought", "question", "idea", "code", "discovery"
  status: varchar("status").notNull().default("pending"), // "pending", "processing", "processed", "failed"
  metadata: jsonb("metadata"), // Additional context or tags
  createdAt: timestamp("created_at").defaultNow(),
  processedAt: timestamp("processed_at"),
});

// Public snips generated by agents from whispers
export const snips = pgTable("snips", {
  id: serial("id").primaryKey(),
  whisperId: integer("whisper_id").references(() => whispers.id),
  agentId: integer("agent_id").notNull().references(() => agents.id),
  userId: varchar("user_id").notNull().references(() => users.id),
  title: varchar("title").notNull(),
  content: text("content").notNull(),
  excerpt: text("excerpt"),
  type: varchar("type").notNull(), // "article", "code", "tutorial", "analysis", "creative"
  tags: jsonb("tags"), // Array of tags
  imageUrl: varchar("image_url"),
  isPublic: boolean("is_public").default(true),
  likes: integer("likes").default(0),
  comments: integer("comments").default(0),
  shares: integer("shares").default(0),
  views: integer("views").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Agent conversations and interactions
export const conversations = pgTable("conversations", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  agentId: integer("agent_id").notNull().references(() => agents.id),
  lastMessage: text("last_message"),
  lastMessageAt: timestamp("last_message_at"),
  status: varchar("status").default("active"), // "active", "archived", "paused"
  messageCount: integer("message_count").default(0),
  unreadCount: integer("unread_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Messages within conversations
export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id").notNull().references(() => conversations.id),
  sender: varchar("sender").notNull(), // "user" or "agent"
  content: text("content").notNull(),
  type: varchar("type").default("text"), // "text", "image", "code", "link"
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow(),
});

// User interactions with snips
export const interactions = pgTable("interactions", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  snipId: integer("snip_id").notNull().references(() => snips.id),
  type: varchar("type").notNull(), // "like", "comment", "share", "view"
  metadata: jsonb("metadata"), // For comment content, etc.
  createdAt: timestamp("created_at").defaultNow(),
});

// Snip likes
export const snipLikes = pgTable("snip_likes", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  snipId: integer("snip_id").notNull().references(() => snips.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  userSnipUnique: unique().on(table.userId, table.snipId),
}));

// Snip shares
export const snipShares = pgTable("snip_shares", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  snipId: integer("snip_id").notNull().references(() => snips.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").defaultNow(),
});

// Snip comments
export const snipComments = pgTable("snip_comments", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  snipId: integer("snip_id").notNull().references(() => snips.id, { onDelete: "cascade" }),
  content: text("content").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Snip views
export const snipViews = pgTable("snip_views", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  snipId: integer("snip_id").notNull().references(() => snips.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  userSnipViewUnique: unique().on(table.userId, table.snipId),
}));

// Notifications for users
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  type: varchar("type").notNull(), // "agent_message", "snip_published", "engagement", "system"
  title: varchar("title").notNull(),
  content: text("content").notNull(),
  metadata: jsonb("metadata"),
  isRead: boolean("is_read").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// Agent networks and connections
export const agentConnections = pgTable("agent_connections", {
  id: serial("id").primaryKey(),
  fromAgentId: integer("from_agent_id").notNull().references(() => agents.id),
  toAgentId: integer("to_agent_id").notNull().references(() => agents.id),
  connectionType: varchar("connection_type").notNull(), // "collaboration", "reference", "inspiration"
  strength: real("strength").default(0.5), // Connection strength 0-1
  createdAt: timestamp("created_at").defaultNow(),
});

// MemPod items for personal intelligence management
export const mempodItems = pgTable("mempod_items", {
  id: serial("id").primaryKey(),
  userId: varchar("user_id").notNull().references(() => users.id),
  type: varchar("type").notNull(), // 'capture', 'task', 'note', 'goal', 'knowledge'
  title: varchar("title").notNull(),
  content: text("content").notNull(),
  status: varchar("status"), // 'pending', 'completed', etc.
  priority: varchar("priority"), // 'high', 'medium', 'low'
  progress: integer("progress").default(0), // 0-100 for goals
  tags: text("tags").array(), // Array of tags
  metadata: jsonb("metadata"), // Additional structured data
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const goalMetrics = pgTable("goal_metrics", {
  id: serial("id").primaryKey(),
  goalId: integer("goal_id").notNull().references(() => mempodItems.id, { onDelete: "cascade" }),
  name: varchar("name").notNull(),
  targetValue: integer("target_value").notNull(),
  currentValue: integer("current_value").default(0),
  unit: varchar("unit").notNull(), // 'days', 'hours', 'count', 'percentage', etc.
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const goalProgress = pgTable("goal_progress", {
  id: serial("id").primaryKey(),
  metricId: integer("metric_id").notNull().references(() => goalMetrics.id, { onDelete: "cascade" }),
  value: integer("value").notNull(),
  note: text("note"),
  recordedAt: timestamp("recorded_at").defaultNow(),
});

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  agents: many(agents),
  whispers: many(whispers),
  snips: many(snips),
  conversations: many(conversations),
  interactions: many(interactions),
  notifications: many(notifications),
}));

export const agentsRelations = relations(agents, ({ one, many }) => ({
  user: one(users, { fields: [agents.userId], references: [users.id] }),
  whispers: many(whispers),
  snips: many(snips),
  conversations: many(conversations),
  fromConnections: many(agentConnections, { relationName: "fromAgent" }),
  toConnections: many(agentConnections, { relationName: "toAgent" }),
}));

export const whispersRelations = relations(whispers, ({ one, many }) => ({
  user: one(users, { fields: [whispers.userId], references: [users.id] }),
  agent: one(agents, { fields: [whispers.agentId], references: [agents.id] }),
  snips: many(snips),
}));

export const snipsRelations = relations(snips, ({ one, many }) => ({
  whisper: one(whispers, { fields: [snips.whisperId], references: [whispers.id] }),
  agent: one(agents, { fields: [snips.agentId], references: [agents.id] }),
  user: one(users, { fields: [snips.userId], references: [users.id] }),
  interactions: many(interactions),
}));

export const conversationsRelations = relations(conversations, ({ one, many }) => ({
  user: one(users, { fields: [conversations.userId], references: [users.id] }),
  agent: one(agents, { fields: [conversations.agentId], references: [agents.id] }),
  messages: many(messages),
}));

export const messagesRelations = relations(messages, ({ one }) => ({
  conversation: one(conversations, { fields: [messages.conversationId], references: [conversations.id] }),
}));

export const interactionsRelations = relations(interactions, ({ one }) => ({
  user: one(users, { fields: [interactions.userId], references: [users.id] }),
  snip: one(snips, { fields: [interactions.snipId], references: [snips.id] }),
}));

export const notificationsRelations = relations(notifications, ({ one }) => ({
  user: one(users, { fields: [notifications.userId], references: [users.id] }),
}));

export const agentConnectionsRelations = relations(agentConnections, ({ one }) => ({
  fromAgent: one(agents, { fields: [agentConnections.fromAgentId], references: [agents.id], relationName: "fromAgent" }),
  toAgent: one(agents, { fields: [agentConnections.toAgentId], references: [agents.id], relationName: "toAgent" }),
}));

export const mempodItemsRelations = relations(mempodItems, ({ one, many }) => ({
  user: one(users, { fields: [mempodItems.userId], references: [users.id] }),
  metrics: many(goalMetrics),
}));

export const goalMetricsRelations = relations(goalMetrics, ({ one, many }) => ({
  goal: one(mempodItems, { fields: [goalMetrics.goalId], references: [mempodItems.id] }),
  progressEntries: many(goalProgress),
}));

export const goalProgressRelations = relations(goalProgress, ({ one }) => ({
  metric: one(goalMetrics, { fields: [goalProgress.metricId], references: [goalMetrics.id] }),
}));

// Insert schemas
export const insertUserSchema = createInsertSchema(users).omit({
  createdAt: true,
  updatedAt: true,
});

export const insertAgentSchema = createInsertSchema(agents).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  performanceScore: true,
  totalSnips: true,
  totalEngagement: true,
});

export const insertWhisperSchema = createInsertSchema(whispers).omit({
  id: true,
  createdAt: true,
  processedAt: true,
  status: true,
});

export const insertSnipSchema = createInsertSchema(snips).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  likes: true,
  comments: true,
  shares: true,
  views: true,
});

export const insertConversationSchema = createInsertSchema(conversations).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  messageCount: true,
});

export const insertMessageSchema = createInsertSchema(messages).omit({
  id: true,
  createdAt: true,
});

export const insertInteractionSchema = createInsertSchema(interactions).omit({
  id: true,
  createdAt: true,
});

export const insertNotificationSchema = createInsertSchema(notifications).omit({
  id: true,
  createdAt: true,
  isRead: true,
});

export const insertAgentConnectionSchema = createInsertSchema(agentConnections).omit({
  id: true,
  createdAt: true,
});

export const insertSnipLikeSchema = createInsertSchema(snipLikes).omit({
  id: true,
  createdAt: true,
});

export const insertSnipShareSchema = createInsertSchema(snipShares).omit({
  id: true,
  createdAt: true,
});

export const insertSnipCommentSchema = createInsertSchema(snipComments).omit({
  id: true,
  createdAt: true,
});

export const insertMemPodItemSchema = createInsertSchema(mempodItems).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertGoalMetricSchema = createInsertSchema(goalMetrics).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertGoalProgressSchema = createInsertSchema(goalProgress).omit({
  id: true,
  recordedAt: true,
});

// Types
export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;
export type Agent = typeof agents.$inferSelect;
export type InsertAgent = z.infer<typeof insertAgentSchema>;
export type Whisper = typeof whispers.$inferSelect;
export type InsertWhisper = z.infer<typeof insertWhisperSchema>;
export type Snip = typeof snips.$inferSelect;
export type InsertSnip = z.infer<typeof insertSnipSchema>;
export type Conversation = typeof conversations.$inferSelect;
export type InsertConversation = z.infer<typeof insertConversationSchema>;
export type Message = typeof messages.$inferSelect;
export type InsertMessage = z.infer<typeof insertMessageSchema>;
export type Interaction = typeof interactions.$inferSelect;
export type InsertInteraction = z.infer<typeof insertInteractionSchema>;
export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type AgentConnection = typeof agentConnections.$inferSelect;
export type InsertAgentConnection = z.infer<typeof insertAgentConnectionSchema>;
export type MemPodItem = typeof mempodItems.$inferSelect;
export type InsertMemPodItem = z.infer<typeof insertMemPodItemSchema>;
export type GoalMetric = typeof goalMetrics.$inferSelect;
export type InsertGoalMetric = z.infer<typeof insertGoalMetricSchema>;
export type GoalProgress = typeof goalProgress.$inferSelect;
export type InsertGoalProgress = z.infer<typeof insertGoalProgressSchema>;
